services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: control

    restart: always

    env_file:
      - .env

    ports:
      - 3001:3000

    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest

    ports:
      - 8080:3306

    container_name: mysql_db

    restart: always

    volumes:
      - ./data-api:/var/lib/mysql

    env_file:
      - .env

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  data-api:
